USE themoviedb;
CREATE TABLE unconfirmed(
    email VARCHAR(150) NOT NULL PRIMARY KEY UNIQUE,
    password VARCHAR(150) NOT NULL,
    confirmation_token VARCHAR(150) NOT NULL
);
CREATE TABLE users(
    email VARCHAR(150) NOT NULL PRIMARY KEY UNIQUE,
    password VARCHAR(150) NOT NULL
);
CREATE TABLE sessions(
    token VARCHAR(150) NOT NULL UNIQUE,
    email VARCHAR(150) NOT NULL,
    FOREIGN KEY (email) REFERENCES users(email)
    ON DELETE CASCADE ON UPDATE CASCADE
);
